name: Build site

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kunalnagar/ruby-node
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
      - name: Lint code + YML
        run: |
          npm run lint
          npm run lint:github
      - name: Create Storybook build
        run: npm run build
