name: Release storybook

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*.*'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Lint code + YML
        run: yarn lint
      - name: Create build
        run: yarn build
      - name: Create Storybook build
        run: yarn build:storybook
      - name: Release
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release
