name: Release storybook

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*.*'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Lint code + YML
        run: npm run lint
      - name: Create build
        run: npm run build
      - name: Create Storybook build
        run: npm run build:storybook
      - name: Release
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release
